apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: nodejs-grpc-test
build:
  local:
    push: false
    useDockerCLI: true
  artifacts:
    - image: nodevoto
      docker:
        dockerfile: Dockerfile
      sync:
        infer:
          - '**/*.js'
manifests:
  rawYaml:
    - k8s/deployment.yml
